- name: update and upgrade apt
  become: True
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # one day

- name: install the latest version of fail2ban
  become: True
  package:
    name: fail2ban
    state: latest

- name: add a new rule
  become: True
  lineinfile:
    path: "/etc/fail2ban/filter.d/{{ item.0.name }}.conf"
    insertafter: "^failregex ="
    line: '            {{ item.1 }}'
    state: present
  with_subelements:
    - "{{ config }}"
    - append
  notify: reload fail2ban

- name: delete the rule
  become: True
  lineinfile:
    path: /etc/fail2ban/filter.d/sshd.conf
    regexp: "maximum authentication"
    state: absent
  notify: reload fail2ban
  when: False

