---
- name: update and upgrade apt
  become: True
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # one day

- name: install the latest version of fail2ban
  become: True
  package:
    name: fail2ban
    state: latest
  notify: start fail2ban

- name: start fail2ban
  become: True
  service:
    name: fail2ban
    state: started

- name: add new rules
  become: True
  lineinfile:
    path: "/etc/fail2ban/filter.d/{{ item.0.name }}.conf"
    insertafter: "^failregex ="
    line: "            {{ item.1 }}"
    state: present
  with_subelements:
    - "{{ config }}"
    - rule
  notify: reload fail2ban

- name: delete the rules
  become: True
  lineinfile:
    path: "/etc/fail2ban/filter.d/{{ item.0.name }}.conf"
    line: "            {{ item.1 }}"
    state: absent
  with_subelements:
    - "{{ config }}"
    - rule
  notify: reload fail2ban

- name: stop fail2ban
  become: True
  service:
    name: fail2ban
    state: stopped
...
